return {
	["username"] = "Guest",
	["blind_col"] = 1,
	["server_url"] = "balatro.virtualized.dev",
	["server_port"] = 8788,
	["lan_broadcast_port"] = 8789,
	["lan_default_port"] = 8788,
	["lan_bind_ip"] = "",
	["logging"] = false,
	["misprint_display"] = true,
	["integrations"] = {
		["TheOrder"] = true,
		["Preview"] = false,
	},
	["unlocked"] = true,
	["preview"] = {},
	["joker_stats"] = {},
	["match_history"] = {},
	["ghost_replays"] = {},
}
